SpectraLogic/rio_client

src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/main/kotlin/com/spectralogic/rioclient/Device.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/main/kotlin/com/spectralogic/rioclient/Token.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

Added Diva, Flashnet, & Tbpfr

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/main/kotlin/com/spectralogic/rioclient/Extensions.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt

Three fixes:
* Reduce distribution size by replacing dependencies with brand new Kotlin 1.6 methods.
* Replace int with long in page size because I'm paranoid about the size of some of our clients systems
* Bump versions including Kotlin 1.6

Escp 3420 1

---

src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

ESCP-3501: Add metadata batch update call and test

---

src/main/kotlin/com/spectralogic/rioclient/Device.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

1 - Add accessKey to VailResponse
2 - Refactor all delete requests to return a response instead of just a boolean
I will have to refactor RioBroker CLI and RioCruise accordingly.  
Doing the same for all HEAD commands will be next.

Refactor delete response

---

src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

Added object, method, and test for broker agent update

ESCP-3527: broker agent update

---

src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

Once RioClient library gets updated, then I will have another PR for RioBroker.

ESCP-3537: Refactor agent update and correctly process no request body

---

src/main/kotlin/com/spectralogic/rioclient/Device.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt

Then I can write a dev-integration test in RioBroker

ESCP-3726: Add method for listing endpoint objects

---

src/main/kotlin/com/spectralogic/rioclient/Broker.kt

Found during RioBroker dev-integration testing

ESCP-3391: Add missing class extension

---

build.gradle.kts

* Target Java 17 for JVM bytecode
* Upgrade jackson BOM

JVM target 17

---

build.gradle.kts
project_files/owasp/dependency-check-suppression.xml

(cherry picked from commit e9fec11d80d3d943b7d2fb2aa240d1adfcbb8d06)

Update depcheck plugin and add suppression for overly broad CPE

---

src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

(cherry picked from commit 04b1c3e5e7f8f62082881dfd7522feb45de7c963)

ESCP-3973: Added fail-fast to createArchiveJob

---

build.gradle.kts
settings.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/General.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt

@david-limbach This was supposed to just be a simple bump, I noticed I needed to grab the http code value. Does that seem correct to you?

Kotlin 1.9.22 version bump

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

To support integration test on job search by file name in RioBroker

ESCP-3426: Add fileName option to listJobs, add test, update version

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

- Added data class for NAS agent
- Added test for NAS agent
- Modified test to accept alternate Rio login/password
- Fixed behavior issue change in Spectra Device test
- Fixed logic error in Client Data test, left over data from previous run

NAS agent plus

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/main/kotlin/com/spectralogic/rioclient/TokenClient.kt

Still seeing a slowdown in WF after building RioClient so many times.

Rio client close

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/Authentication.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

Needs cherry pick to 1x (sigh)

ESCP-4721: User maintenance methods

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/HttpClientFactory.kt
src/main/kotlin/com/spectralogic/rioclient/Token.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

- Bump version
- Update token response to include new fields
- Fix test

ESCP-4721: Include new fields in new login token response MAIN

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/Token.kt
src/main/kotlin/com/spectralogic/rioclient/TokenClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClient_Test.kt

- Bump version
- Update token response to include new fields
- Fix test

ESCP-4721: Include new fields in new login token response 1x

---

build.gradle.kts
src/main/kotlin/com/spectralogic/rioclient/Broker.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/test/kotlin/com/spectralogic/rioclient/RioClientTest.kt

- removed duplicate response data class
- fixed tests to match updated error message

ESCP-5085: includeAgentCopies option to listObjects(), plus test

---

src/main/kotlin/com/spectralogic/rioclient/Device.kt
src/main/kotlin/com/spectralogic/rioclient/HttpClientFactory.kt
src/main/kotlin/com/spectralogic/rioclient/RioClient.kt
src/main/kotlin/com/spectralogic/rioclient/RioGroups.kt
src/test/kotlin/com/spectralogic/rioclient/RioClientTest.kt

I believe these are all the new endpoints from swagger plus removing deleteCluster.
It seems several of these are just ktlint.

ESCP-5339: Add new endpoints for groups and domains
